// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


// tinymce

//Unit
import UnitInstructionTinymceController from "./tinymce/unit/unit_instruction_tinymce_controller.js"
application.register("unit_instruction_tinymce", UnitInstructionTinymceController)
import UnitSolvesTheProblemTinymceController from "./tinymce/unit/unit_solves_the_problem_tinymce_controller.js"
application.register("unit_solves_the_problem_tinymce", UnitSolvesTheProblemTinymceController)
import UnitSourcesTinymceController from "./tinymce/unit/unit_sources_tinymce_controller.js"
application.register("unit_sources_tinymce", UnitSourcesTinymceController)
import UnitAdditionalInformationTinymceController from "./tinymce/unit/unit_additional_information_tinymce_controller.js"
application.register("unit_additional_information_tinymce", UnitAdditionalInformationTinymceController)
import UnitDescriptionTinymceController from "./tinymce/unit/unit_description_tinymce_controller.js"
application.register("unit_description_tinymce", UnitDescriptionTinymceController)


//UnitUsageExample
import UnitUsageExampleDescriptionTinymceController from "./tinymce/unit/unit_usage_example_description_tinymce_controller.js"
application.register("unit_usage_example_description_tinymce", UnitUsageExampleDescriptionTinymceController)
import UnitUsageExampleSourcesTinymceController from "./tinymce/unit/unit_usage_example_sources_tinymce_controller.js"
application.register("unit_usage_example_sources_tinymce", UnitUsageExampleSourcesTinymceController)

import UsageExamplesSerpController from "./usage_examples_serp_controller.js"
application.register("usage_examples_serp", UsageExamplesSerpController)



//Improvements
import ImprovementContentTinymceController from "./tinymce/improvements/improvement_content_tinymce_controller.js"
application.register("improvement_content_tinymce", ImprovementContentTinymceController)
import ImprovementSourcesTinymceController from "./tinymce/improvements/improvement_sources_tinymce_controller.js"
application.register("improvement_sources_tinymce", ImprovementSourcesTinymceController)


import ImprovementsInfiniteScrollController from "./improvements_infinite_scroll_controller.js"
application.register("improvements_infinite_scroll", ImprovementsInfiniteScrollController)


// Algorithms
//// Steps
// import StepsDragController from "./algorithms/steps_drag_controller.js"
// application.register("steps_drag", StepsDragController)

import NodesDragController from "./algorithms/nodes_drag_controller.js"
application.register("nodes_drag", NodesDragController)


import StepAccordionController from "./algorithms/step_accordion_controller.js"
application.register("step_accordion", StepAccordionController)

import StepFinishCheckTinymceController from "./tinymce/step/step_finish_check_tinymce_controller"
application.register("step_finish_check_tinymce", StepFinishCheckTinymceController)

// import SubstepsDragController from "./algorithms/substeps_drag_controller.js"
// application.register("substeps_drag", SubstepsDragController)

import AlgorithmStepTypeSelectController from "./algorithms/algorithm_step_type_select_controller.js"
application.register("algorithm_step_type_select", AlgorithmStepTypeSelectController)

import StepTypeOptionsModalController from "./algorithms/step_type_options_modal_controller.js"
application.register("step_type_options_modal", StepTypeOptionsModalController)

import StepsNestedFormController from "./algorithms/steps_nested_form_controller.js"
application.register("steps_nested_form", StepsNestedFormController)

import DynamicStepFormController from "./algorithms/dynamic_step_form_controller.js"
application.register("dynamic_step_form", DynamicStepFormController)

import ScrollToStepBeginningController from "./algorithms/scroll_to_step_beginning_controller.js"
application.register("scroll_to_step_beginning", ScrollToStepBeginningController)

// import DroppableController from 'stimulus-droppable';
// application.register('droppable', DroppableController);




// Instructions

// autocomplete (will be added)
// import AutocompleteController from "./autocomplete_controller"
// application.register("autocomplete", AutocompleteController)

// search - rename so search instruction
import SearhInstructionsController from "./instructions/search_instructions_controller"
application.register("search_instructions", SearhInstructionsController)

import RemoteSelectInstructionController from "./instructions/remote_select_instruction_controller"
application.register("remote_select_instruction", RemoteSelectInstructionController)

import SelectInstructionModalController from "./instructions/select_instruction_modal_controller"
application.register("select_instruction_modal", SelectInstructionModalController)

import SelectInstructionTabsController from "./instructions/select_instruction_tabs_controller"
application.register("select_instruction_tabs", SelectInstructionTabsController)



// shared

// modals
// not in use?
import ModalController from "./shared/modal_controller"
application.register("modal", ModalController)
// tabs
import TabsController from "./shared/tabs_controller"
application.register("tabs", TabsController)

import TagsController from "./shared/tags_controller"
application.register("tags", TagsController)

import addActionOptionsModalController from "./shared/add_action_options_modal_controller"
application.register("add_action_options_modal", addActionOptionsModalController)

import technologyAsynchRenderingController from "./shared/technology_asynch_rendering_controller"
application.register("technology_asynch_rendering", technologyAsynchRenderingController)

import nodeAccordionController from "./shared/node_accordion_controller"
application.register("node_accordion", nodeAccordionController)

import contentAreaController from "./shared/content_area_controller"
application.register("content_area", contentAreaController)


// navigation
import NavigationSearchFormController from "./navigation/navigation_search_form_controller"
application.register("navigation_search_form", NavigationSearchFormController)


// Objects
import ObjectCreationModalController from "./objects/object_creation_options_modal_controller"
application.register("object_creation_options_modal", ObjectCreationModalController)


import InterfaceGroupsDragController from "./interface_groups/interface_groups_drag_controller"
application.register("interface_groups_drag", InterfaceGroupsDragController)

import InterfaceGroupManagementOptionsButtonController from "./interface_groups/interface_group_management_options_button_controller"
application.register("interface_group_management_options_button", InterfaceGroupManagementOptionsButtonController)




// Dashboard
import DashboardTabsController from "./dashboard/dashboard_tabs_controller"
application.register("dashboard_tabs", DashboardTabsController)

import DashboardTechnologiesController from "./dashboard/dashboard_technologies_controller"
application.register("dashboard_technologies", DashboardTechnologiesController)

// Folder
import FolderItemsController from "./folder/folder_items_controller"
application.register("folder_items", FolderItemsController)


// Technologies
// import TechnologiesController from "./technologies_controller"
// application.register("technologies", TechnologiesController)

import TechSerpSearchController from "./technologies/tech_serp_search_controller"
application.register("tech_serp_search", TechSerpSearchController)

import TechSerpTabsController from "./technologies/tech_serp_tabs_controller"
application.register("tech_serp_tabs", TechSerpTabsController)

import TechSerpTagsInputController from "./technologies/tech_serp_tags_input_controller"
application.register("tech_serp_tags_input", TechSerpTagsInputController)

import TechSerpUsersInputController from "./technologies/tech_serp_users_input_controller"
application.register("tech_serp_users_input", TechSerpUsersInputController)


// Users (forms,inputs)
import AvatarInputController from "./users/users_avatar_input_controller"
application.register("users_avatar_input", AvatarInputController)


// TOC
import TocScrollingController from "./toc/toc_scrolling_controller"
application.register("toc_scrolling", TocScrollingController)


//SimpleClassAttributes
import SimpleClassAttributePreviewController from "./simple_class_attributes/simple_class_attribute_preview_controller"
application.register("simple_class_attribute_preview", SimpleClassAttributePreviewController)

//technologies pick module
import TechnologiesPickModalController from "./technologies_pick/technologies_pick_modal_controller"
application.register("technologies_pick_modal", TechnologiesPickModalController)
import RemoteTechnologiesPickController from "./technologies_pick/remote_technologies_pick_controller"
application.register("remote_technologies_pick", RemoteTechnologiesPickController)

// InterfaceMember
import InterfaceMembersDragController from "./interface_members/interface_members_drag_controller"
application.register("interface_members_drag", InterfaceMembersDragController)

// SimpleClass
import SimpleClassTreeMapController from "./simple_class/tree_map/simple_class_tree_map_controller"
application.register("simple_class_tree_map", SimpleClassTreeMapController)

import ClassTreeMapModalController from "./simple_class/tree_map/class_tree_map_modal_controller"
application.register("class_tree_map_modal", ClassTreeMapModalController)


// Technology pick
// import RemoteTechnologyPickController from "./technology_pick/remote_technology_pick_controller"
// application.register("remote_technology_pick", RemoteTechnologyPickController)

import TechnologyPickModalController from "./technology_pick/technology_pick_modal_controller"
application.register("technology_pick_modal", TechnologyPickModalController)


