// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


// tinymce

//Unit
import UnitInstructionTinymceController from "./tinymce/unit/unit_instruction_tinymce_controller.js"
application.register("unit_instruction_tinymce", UnitInstructionTinymceController)
import UnitSolvesTheProblemTinymceController from "./tinymce/unit/unit_solves_the_problem_tinymce_controller.js"
application.register("unit_solves_the_problem_tinymce", UnitSolvesTheProblemTinymceController)
import UnitSourcesTinymceController from "./tinymce/unit/unit_sources_tinymce_controller.js"
application.register("unit_sources_tinymce", UnitSourcesTinymceController)
import UnitAdditionalInformationTinymceController from "./tinymce/unit/unit_additional_information_tinymce_controller.js"
application.register("unit_additional_information_tinymce", UnitAdditionalInformationTinymceController)


//UnitUsageExample
import UnitUsageExampleDescriptionTinymceController from "./tinymce/unit/unit_usage_example_description_tinymce_controller.js"
application.register("unit_usage_example_description_tinymce", UnitUsageExampleDescriptionTinymceController)
import UnitUsageExampleSourcesTinymceController from "./tinymce/unit/unit_usage_example_sources_tinymce_controller.js"
application.register("unit_usage_example_sources_tinymce", UnitUsageExampleSourcesTinymceController)

import UsageExamplesSerpController from "./usage_examples_serp_controller.js"
application.register("usage_examples_serp", UsageExamplesSerpController)



//Improvements
import ImprovementContentTinymceController from "./tinymce/improvements/improvement_content_tinymce_controller.js"
application.register("improvement_content_tinymce", ImprovementContentTinymceController)
import ImprovementSourcesTinymceController from "./tinymce/improvements/improvement_sources_tinymce_controller.js"
application.register("improvement_sources_tinymce", ImprovementSourcesTinymceController)


import ImprovementsInfiniteScrollController from "./improvements_infinite_scroll_controller.js"
application.register("improvements_infinite_scroll", ImprovementsInfiniteScrollController)

// Steps
import StepsDragController from "./steps_drag_controller.js"
application.register("steps_drag", StepsDragController)

import StepAccordionController from "./step_accordion_controller.js"
application.register("step_accordion", StepAccordionController)

import StepFinishCheckTinymceController from "./tinymce/step/step_finish_check_tinymce_controller"
application.register("step_finish_check_tinymce", StepFinishCheckTinymceController)

// shared

// modals
// not in use?
import ModalController from "./shared/modal_controller"
application.register("modal", ModalController)
// tabs
import TabsController from "./shared/tabs_controller"
application.register("tabs", TabsController)







// Instructions

// autocomplete
// import AutocompleteController from "./autocomplete_controller"
// application.register("autocomplete", AutocompleteController)

// search - rename so search instruction
import SearhInstructionsController from "./instructions/search_instructions_controller"
application.register("search_instructions", SearhInstructionsController)

import RemoteSelectInstructionController from "./instructions/remote_select_instruction_controller"
application.register("remote_select_instruction", RemoteSelectInstructionController)

import SelectInstructionModalController from "./instructions/select_instruction_modal_controller"
application.register("select_instruction_modal", SelectInstructionModalController)

import SelectInstructionTabsController from "./instructions/select_instruction_tabs_controller"
application.register("select_instruction_tabs", SelectInstructionTabsController)