// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


// Tinymce:
// 1.1 Unit
import UnitInstructionTinymceController from "./tinymce/unit/unit_instruction_tinymce_controller.js"
application.register("unit_instruction_tinymce", UnitInstructionTinymceController)
import UnitSolvesTheProblemTinymceController from "./tinymce/unit/unit_solves_the_problem_tinymce_controller.js"
application.register("unit_solves_the_problem_tinymce", UnitSolvesTheProblemTinymceController)
import UnitSourcesTinymceController from "./tinymce/unit/unit_sources_tinymce_controller.js"
application.register("unit_sources_tinymce", UnitSourcesTinymceController)
import UnitAdditionalInformationTinymceController from "./tinymce/unit/unit_additional_information_tinymce_controller.js"
application.register("unit_additional_information_tinymce", UnitAdditionalInformationTinymceController)
import UnitDescriptionTinymceController from "./tinymce/unit/unit_description_tinymce_controller.js"
application.register("unit_description_tinymce", UnitDescriptionTinymceController)

// 1.2 UsageExample
import UsageExampleContentTinymceController from "./tinymce/usage_example/usage_example_content_tinymce_controller.js"
application.register("usage_example_content_tinymce", UsageExampleContentTinymceController)
import UsageExampleSourcesTinymceController from "./tinymce/usage_example/usage_example_sources_tinymce_controller.js"
application.register("usage_example_sources_tinymce", UsageExampleSourcesTinymceController)
import UsageExamplesSerpController from "./usage_examples_serp_controller.js"
application.register("usage_examples_serp", UsageExamplesSerpController)
import UsageExamplesDisplayInfinityScrollController from "./usage_examples/usage_examples_display_infinity_scroll_controller"
application.register("usage_examples_display_infinity_scroll", UsageExamplesDisplayInfinityScrollController)


//1.3 Improvement
import ImprovementContentTinymceController from "./tinymce/improvements/improvement_content_tinymce_controller.js"
application.register("improvement_content_tinymce", ImprovementContentTinymceController)
import ImprovementSourcesTinymceController from "./tinymce/improvements/improvement_sources_tinymce_controller.js"
application.register("improvement_sources_tinymce", ImprovementSourcesTinymceController)

// 1.4 Repository
import RepositoryDescriptionTinymceController from "./tinymce/repositories/repository_description_tinymce_controller.js"
application.register("repository_description_tinymce", RepositoryDescriptionTinymceController)

// 1.5 Folder
import FolderDescriptionTinymceController from "./tinymce/folders/folder_description_tinymce_controller.js"
application.register("folder_description_tinymce", FolderDescriptionTinymceController)

// 1.6 SimpleClass
import SimpleClassDescriptionTinymceController from "./tinymce/simple_classes/simple_class_description_tinymce_controller.js"
application.register("simple_class_description_tinymce", SimpleClassDescriptionTinymceController)

// 1.7 Step
import StepFinishCheckTinymceController from "./tinymce/step/step_finish_check_tinymce_controller"
application.register("step_finish_check_tinymce", StepFinishCheckTinymceController)

import StepAdditionalInformationTinymceController from "./tinymce/step/step_additional_information_tinymce_controller"
application.register("step_additional_information_tinymce", StepAdditionalInformationTinymceController)

import StepContentTinymceController from "./tinymce/step/step_content_tinymce_controller"
application.register("step_content_tinymce", StepContentTinymceController)

import StepDescriptionTinymceController from "./tinymce/step/step_description_tinymce_controller"
application.register("step_description_tinymce", StepDescriptionTinymceController)

import StepSolvesTheProblemTinymceController from "./tinymce/step/step_solves_the_problem_tinymce_controller"
application.register("step_solves_the_problem_tinymce", StepSolvesTheProblemTinymceController)

import StepSourcesTinymceController from "./tinymce/step/step_sources_tinymce_controller"
application.register("step_sources_tinymce", StepSourcesTinymceController)

// Improvements
import ImprovementsInfiniteScrollController from "./improvements/improvements_infinite_scroll_controller.js"
application.register("improvements_infinite_scroll", ImprovementsInfiniteScrollController)


// Algorithms
import NodesDragController from "./algorithms/nodes_drag_controller.js"
application.register("nodes_drag", NodesDragController)


import StepAccordionController from "./algorithms/step_accordion_controller.js"
application.register("step_accordion", StepAccordionController)

import AlgorithmStepTypeSelectController from "./algorithms/algorithm_step_type_select_controller.js"
application.register("algorithm_step_type_select", AlgorithmStepTypeSelectController)

import StepTypeOptionsModalController from "./algorithms/step_type_options_modal_controller.js"
application.register("step_type_options_modal", StepTypeOptionsModalController)

import StepsNestedFormController from "./algorithms/steps_nested_form_controller.js"
application.register("steps_nested_form", StepsNestedFormController)

import DynamicStepFormController from "./algorithms/dynamic_step_form_controller.js"
application.register("dynamic_step_form", DynamicStepFormController)

import ScrollToStepBeginningController from "./algorithms/scroll_to_step_beginning_controller.js"
application.register("scroll_to_step_beginning", ScrollToStepBeginningController)

// Attachments
import AttachmentsNestedFormController from "./attachments/attachments_nested_form_controller.js"
application.register("attachments_nested_form", AttachmentsNestedFormController)

import RemoteSelectAttachmentController from "./attachments/remote_select_attachment_controller.js"
application.register("remote_select_attachment", RemoteSelectAttachmentController)

import AttachmentPreviewController from "./attachments/attachment_preview_controller.js"
application.register("attachment_preview", AttachmentPreviewController)


// Instructions

// autocomplete (will be added)
// import AutocompleteController from "./autocomplete_controller"
// application.register("autocomplete", AutocompleteController)

// search - rename so search instruction
import SearchInstructionsController from "./instructions/search_instructions_controller"
application.register("search_instructions", SearchInstructionsController)

import RemoteSelectInstructionController from "./instructions/remote_select_instruction_controller"
application.register("remote_select_instruction", RemoteSelectInstructionController)

import SelectInstructionModalController from "./instructions/select_instruction_modal_controller"
application.register("select_instruction_modal", SelectInstructionModalController)

import SelectInstructionTabsController from "./instructions/select_instruction_tabs_controller"
application.register("select_instruction_tabs", SelectInstructionTabsController)



// shared

// modals
// not in use?
import ModalController from "./shared/modal_controller"
application.register("modal", ModalController)
// tabs
import TabsController from "./shared/tabs_controller"
application.register("tabs", TabsController)

import TagsController from "./shared/tags_controller"
application.register("tags", TagsController)

import addActionOptionsModalController from "./shared/add_action_options_modal_controller"
application.register("add_action_options_modal", addActionOptionsModalController)

import technologyAsynchRenderingController from "./shared/technology_asynch_rendering_controller"
application.register("technology_asynch_rendering", technologyAsynchRenderingController)

import nodeAccordionController from "./shared/node_accordion_controller"
application.register("node_accordion", nodeAccordionController)

import contentAreaController from "./shared/content_area_controller"
application.register("content_area", contentAreaController)


// navigation
import NavigationSearchFormController from "./navigation/navigation_search_form_controller"
application.register("navigation_search_form", NavigationSearchFormController)


// Objects
import ObjectCreationModalController from "./objects/object_creation_options_modal_controller"
application.register("object_creation_options_modal", ObjectCreationModalController)


// Interface groups
import InterfaceGroupsDragController from "./interface_groups/interface_groups_drag_controller"
application.register("interface_groups_drag", InterfaceGroupsDragController)

import InterfaceGroupManagementOptionsButtonController from "./interface_groups/interface_group_management_options_button_controller"
application.register("interface_group_management_options_button", InterfaceGroupManagementOptionsButtonController)




// Dashboard
import DashboardTabsController from "./dashboard/dashboard_tabs_controller"
application.register("dashboard_tabs", DashboardTabsController)

import DashboardTechnologiesController from "./dashboard/dashboard_technologies_controller"
application.register("dashboard_technologies", DashboardTechnologiesController)

import DashboardRepositoriesController from "./dashboard/dashboard_repositories_controller"
application.register("dashboard_repositories", DashboardRepositoriesController)



// Folder
import FolderItemsController from "./folder/folder_items_controller"
application.register("folder_items", FolderItemsController)

// Repository
import RepositoryItemsController from "./repository/repository_items_controller"
application.register("repository_items", RepositoryItemsController)



// Technologies
// import TechnologiesController from "./technologies_controller"
// application.register("technologies", TechnologiesController)

import TechSerpSearchController from "./technologies/tech_serp_search_controller"
application.register("tech_serp_search", TechSerpSearchController)

import TechSerpTabsController from "./technologies/tech_serp_tabs_controller"
application.register("tech_serp_tabs", TechSerpTabsController)

import TechSerpTagsInputController from "./technologies/tech_serp_tags_input_controller"
application.register("tech_serp_tags_input", TechSerpTagsInputController)

import TechSerpUsersInputController from "./technologies/tech_serp_users_input_controller"
application.register("tech_serp_users_input", TechSerpUsersInputController)


// Users (forms,inputs)
import AvatarInputController from "./users/users_avatar_input_controller"
application.register("users_avatar_input", AvatarInputController)


// TOC
import TocScrollingController from "./toc/toc_scrolling_controller"
application.register("toc_scrolling", TocScrollingController)


//SimpleClassAttributes
import SimpleClassAttributePreviewController from "./simple_class_attributes/simple_class_attribute_preview_controller"
application.register("simple_class_attribute_preview", SimpleClassAttributePreviewController)

//technologies pick module
import TechnologiesPickModalController from "./technologies_pick/technologies_pick_modal_controller"
application.register("technologies_pick_modal", TechnologiesPickModalController)
import RemoteTechnologiesPickController from "./technologies_pick/remote_technologies_pick_controller"
application.register("remote_technologies_pick", RemoteTechnologiesPickController)

// InterfaceMember
import InterfaceMembersDragController from "./interface_members/interface_members_drag_controller"
application.register("interface_members_drag", InterfaceMembersDragController)

import InterfaceMemberAsynchPreviewController from "./interface_members/interface_member_asynch_preview_controller"
application.register("interface_member_asynch_preview", InterfaceMemberAsynchPreviewController)



// SimpleClass
import SimpleClassTreeMapController from "./simple_class/tree_map/simple_class_tree_map_controller"
application.register("simple_class_tree_map", SimpleClassTreeMapController)

import ClassTreeMapModalController from "./simple_class/tree_map/class_tree_map_modal_controller"
application.register("class_tree_map_modal", ClassTreeMapModalController)


// Technology pick
// import RemoteTechnologyPickController from "./technology_pick/remote_technology_pick_controller"
// application.register("remote_technology_pick", RemoteTechnologyPickController)

import TechnologyPickModalController from "./technology_pick/technology_pick_modal_controller"
application.register("technology_pick_modal", TechnologyPickModalController)

// Comments
import CommentReplyController from "./comments/comment_reply_controller"
application.register("comment_reply", CommentReplyController)

import CommentsInfinityScrollController from "./comments/comments_infinity_scroll_controller"
application.register("comments_infinity_scroll", CommentsInfinityScrollController)

//Pages
import UnitPageController from "./pages/unit_page_controller"
application.register("unit_page", UnitPageController)

// LinkAttachments
import RemoteSelectLinkAttachmentController from "./link_attachments/remote_select_link_attachment_controller"
application.register("remote_select_link_attachment", RemoteSelectLinkAttachmentController)

import LinkAttachmentsNestedFromController from "./link_attachments/link_attachments_nested_form_controller"
application.register("link_attachments_nested_form", LinkAttachmentsNestedFromController)

// CheatSheetGroups
import RemoteSelectCheatSheetGroupSectionController from "./cheat_sheet_groups/remote_select_cheat_sheet_group_section_controller"
application.register("remote_select_cheat_sheet_group_section", RemoteSelectCheatSheetGroupSectionController)

import CheatSheetGroupSectionsNestedFormController from "./cheat_sheet_groups/cheat_sheet_group_sections_nested_form_controller"
application.register("cheat_sheet_group_sections_nested_form", CheatSheetGroupSectionsNestedFormController)

